#!/bin/bash
#поиск правильных email адресов в директории
grep  -P -o -r -I "\b([\w\.\-]+)?[\w]+@[\w\-]+[a-zA-Z0-9]+(\.\w+[a-zA-Z0-9]+){1,}\b" ~/* | sort | uniq -u -ic > output.txt
tail -f output.txt

