#!/bin/bash

n=$1
char=*

let "margin = $n-1"
echo "$char : $n : $margin"
for (( i=1; i <= $n; i++  ))
do
    for (( j=1; j <= $margin; j++  ))
    do
	echo -n " "
    done
    for (( z=$i; z >= 1; z--  ))
    do
	echo -n "* "
    done
    echo " "
    let "margin = $margin-1"
done
margin=1
let "n = $n-1"
for (( i=$n; i >=1; i--  ))
do
    for (( j=1; j <= $margin; j++  ))
    do
	echo -n " "
    done
    for (( z=$i; z >= 1; z--  ))
    do
	echo -n "* "
    done
    echo " "
    let "margin = $margin+1"
done