#!/bin/bash
# вывод на экран ромба
size=$1
char=*

if ! [ $1 ]; then
    echo "input size"
    exit
fi

let "even = $1%2"

if [ $even -eq 0 ]; then
    echo "even"
    exit
fi

if [ $1 -eq 1 ]; then
    echo "not a romb"
    exit
fi

let "margin = $size-1"

for (( i=1; i <= $size; i++  ))
do
    for (( j=1; j <= $margin; j++  ))
    do
	echo -n " "
    done
    for (( j=$i; j >= 1; j--  ))
    do
	echo -n "* "
    done
    echo " "
    let "margin = $margin-1"
done

margin=1
let "size = $size-1"
for (( i=$size; i >=1; i--  ))
do
    for (( j=1; j <= $margin; j++  ))
    do
	echo -n " "
    done
    for (( j=$i; j >= 1; j--  ))
    do
	echo -n "* "
    done
    echo " "
    let "margin = $margin+1"
done