#!/bin/bash

name=$1
key=$2

#gcc -Wall $2 $3 $1
#out="$(time ./a.out)"
#echo "$2"
#by="$(wc -c a.out)"
#echo "byte :$by"

echo "------------"

gcc -Wall -O0 $1
echo "-O0"
out="$(time ./a.out)"
by="$(du -b a.out)"
echo "byte :$by"

echo "------------"

gcc -Wall -Os $1
echo "-Os"
out="$(time ./a.out)"
by="$(du -b a.out)"
echo "byte :$by"

echo "------------"

gcc -Wall -O1 $1
echo "-O1"
out="$(time ./a.out)"
by="$(du -b a.out)"
echo "byte :$by"
echo "------------"

gcc -Wall -O2 $1
echo "-O2"
out="$(time ./a.out)"
by="$(du -b a.out)"
echo "byte :$by"

echo "------------"

gcc -Wall -O3 $1
echo "-O3"
out="$(time ./a.out)"
by="$(du -b a.out)"
echo "byte :$by"

echo "------------"

gcc -Wall -O2 -march=native $1
echo "-O2 -march=native"
out="$(time ./a.out)"
by="$(du -b a.out)"
echo "byte :$by"

echo "------------"

gcc -Wall -O3 -march=native $1
echo "-O3 -march=native"
out="$(time ./a.out)"
by="$(du -b a.out)"
echo "byte :$by"

echo "------------"

gcc -Wall -O2 -march=native -funroll-loops $1
echo "-O2 -march=native -funroll-loops"
out="$(time ./a.out)"
by="$(du -b a.out)"
echo "byte :$by"

echo "------------"

gcc -Wall -O3 -march=native -funroll-loops $1
echo "-O3 -march=native -funroll-loops"
out="$(time ./a.out)"
by="$(du -b a.out)"
echo "byte :$by"

echo "-----END!!-------"

gcc -Wall -O2 -march=native -flto $1
out="$(time ./a.out)"
by="$(du -b a.out)"
echo "-O2 -march=native -flto"
echo "byte :$by"

echo "------------"

gcc -Wall -O2 -march=native -fipa-reference $1
out="$(time ./a.out)"
by="$(du -b a.out)"
echo "-O2 -march=native -fipa-reference"
echo "byte :$by"

echo "------------"

gcc -Wall -O2 -march=native -fprofile-generate $1
out="$(time ./a.out)"
by="$(du -b a.out)"
echo "-O2 -march=native -fprofile-generate"
echo "byte :$by"

echo "------------"

gcc -Wall -O2 -march=native -fprofile-use $1
out="$(time ./a.out)"
by="$(du -b a.out)"
echo "-O2 -march=native -fprofile-use"
echo "byte :$by"

echo "------------"

gcc -Wall -O2 -march=native -flto -fprofile-use $1
out="$(time ./a.out)"
by="$(du -b a.out)"
echo "-O2 -march=native -flto -fprofile-use"
echo "byte :$by"


echo "------------"

gcc -Wall -O2 -march=native -fipa-reference -fprofile-use $1
out="$(time ./a.out)"
by="$(du -b a.out)"
echo "-O2 -march=native -fipa-reference -fprofile-use"
echo "byte :$by"


echo "------------"

gcc -Wall -O2 -march=native -flto -fprofile-generate $1
out="$(time ./a.out)"
by="$(du -b a.out)"
echo "-O2 -march=native -flto -fprofile-generate"
echo "byte :$by"

echo "------------"

gcc -Wall -O2 -march=native -fipa-reference -fprofile-generate $1
out="$(time ./a.out)"
by="$(du -b a.out)"
echo "-O2 -march=native -fipa-reference -fprofile-generate"
echo "byte :$by"
